name: WhereRU-CI/CD-workflow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  #Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # 1. Java 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # gradle caching - 빌드 시간 향상
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      
    #Set up Gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    # Github Submodule에서 환경변수 가져오기
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{secrets.CONFIG_TOKEN}}
        submodules: true
        
    # 서브 모듈 변경 점 있으면 update
    - name: Git Submodule Update
      run: |
        git submodule update --remote --recursive
      

    # gradle build
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test

    # DockerHub 로그인
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    # Docker 이미지 빌드 (Main Branch)
    - name: Docker Image Build
      run: docker build --build-arg SPRING_PROFILE=main -t yerim216/where-r-u:latest .

    # Docker Hub 이미지 푸시
    - name: DockerHub push
      run: docker push yerim216/where-r-u:latest
 
    # EC2 서버에 배포
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      id: deploy-prod
      with:
        host: ${{ secrets.SSH_KNOWN_HOSTS }} # EC2 퍼블릭 IPv4 DNS
        username: ${{secrets.SSH_USER}}
        key: ${{ secrets.SSH_PEM_KEY }}
        envs: GITHUB_SHA
        # 주의 : 실행중인 컨테이너 전부 종료
        script: |
          sudo docker stop $(sudo docker ps -a -q)
          sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/where-r-u:latest
          sudo docker run -d -p 8080:8080 --name whereru-main-server -e SPRING_PROFILE=main -e TZ=Asia/Seoul ${{secrets.DOCKERHUB_USERNAME}}/where-r-u:latest
          sudo docker image prune -f
